name: Build
on:
  push:
    branches:
      - main
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - run: git tag ${{github.run_number}}
      - name: Execute Gradle build
        run: ./gradlew :desktop:dist

      - run: |
          wget -O packr-all.jar https://github.com/libgdx/packr/releases/download/4.0.0/packr-all-4.0.0.jar
          java -jar packr-all.jar \
          --platform mac \
          --jdk https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9_openj9-0.24.0/OpenJDK11U-jre_x64_mac_openj9_macosXL_11.0.10_9_openj9-0.24.0.tar.gz \
          --useZgcIfSupportedOs \
          --executable yeeing \
          --classpath desktop/build/libs/desktop.jar \
          --mainclass io.github.inggame.DesktopLauncher \
          --vmargs Xmx1G \
          --output out-mac

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build#${{github.run_number}}"
          automatic_release_tag: "${{github.run_number}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: out-mac/**
          prerelease: false